appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c342c7c3aeb3c070045a8e1
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: jyE0lfOfwp/Xzq5Bm5qzgnqTIkNpqqdYfOg1nqkcfZeVm0a2+NrvvcPAMadzScvTsuQ09DrZzNFoe+qvgkv8YooeG5t9r6WPw2lVrmsgt9Bq1bRSdHiC7xaalHiL/BnVWbzWe6zm3ttzlUTDUHoMS0qNgMIQ9QcSKiFDQ3uEnD/0Qn2Q0YjVzbLN99OqlxKlPIDjLBIQMpmkSd+I+GLVZG9WMkhqylQVBBO4FDEwwcx4hfzNRSA/kMw1gRZlSZdz+IFxMUhJTJc4taOUzl6N6KNigWeDLT/yXcd1yfMi++s+TlhHXmpO9F7XqG2kDC3YuPMZD8keej72QDE0byeNEt55cUzAkimoGIDEMSzck2yqs8fllwFhI83dkRtByQvrg/cMt86WgWGRQmXzozdgiKFCKQg/QFAzqdSPtlFaiO5TQss8dS+xyV4MmQbqg0NuJ4BByttSvjIfIBxa7e0BRMP+mf27KaAW/lo/EUUAHg1K0aHdcK1hpfU0KCQZKfGEvaLwojOWJbq0QAm0qKRDeBk2AEC7Yv6LEjexwVZJq9Q1EQn/aEEkh9aIrPUzfsVEJYvdZnkbSzbiLlsRpzpcvl1DzK7XJOyHJL+Yb10lyJgcMQnu17v8DZHZ7KLJifqGtKErEM0a/E/u8bX5/bNwIQJAhJzSed/6Jcarbe0/GIA=}
